version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mybankdb
      POSTGRES_USER: devadmin
      POSTGRES_PASSWORD: devadmin123pass
    expose:
      - "5432"
  mybank-api:
      build:
        context: ../mybank-api
      ports:
        - "8080:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        - account-service
        - transaction-service
  account-service:
      build:
        context: ../account-service
      expose:
        - "8080"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        - postgres
  transaction-service:
      build:
        context: ../transaction-service
      expose:
        - "8080"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        - postgres